pcall(require, "impatient")
require("win.options")
require("win.keymaps")
require("win.plugins")
require("win.autocommands")
require("win.colorscheme")
require("win.cmp")
require("win.dressing")
require("win.gps")
require("win.lsp")
-- require("win.lspsaga")
require("win.telescope")
require("win.terminal")
require("win.treesitter")
require("win.autopairs")
require("win.comment")
require("win.gitsigns")
require("win.nvim-tree")
require("win.lualine")
require("win.toggleterm")
require("win.indentline")
-- require("win.alpha")
require("win.colorizer")
require("win.tabout")
-- require("stay-centered")
require("illuminate")
