pcall(require, "impatient")
require("win.options")
require("win.keymaps")
require("win.plugins")
require("win.colorscheme")
require("win.autocommands")
require("win.alpha")
require("win.autopairs")
require("win.cmp")
require("win.comment")
require("win.colorizer")
require("win.dressing")
-- require("win.filetype")
require("win.gitsigns")
require("win.illuminate")
require("win.indentline")
require("win.lualine")
require("win.nvim-tree")
require("win.tabout")
require("win.telescope")
require("win.toggleterm")
require("win.treesitter")
require("win.lsp")
require("win.numb")

-- require("win.winbar")
-- require("win.gps")
